import { Book } from "@/db/shema";

export const books: Book[] = [
  {
    id: "1e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A novel set in the Roaring Twenties.",
    image: "https://example.com/gatsby.jpg",
    shelfId: "shelf-1",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "2e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5q",
    title: "1984",
    author: "George Orwell",
    description: "Dystopian novel about totalitarianism.",
    image: "https://example.com/1984.jpg",
    shelfId: "shelf-1",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "3e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5r",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A novel about racial injustice in the Deep South.",
    image: "https://example.com/mockingbird.jpg",
    shelfId: "shelf-2",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "4e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5s",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel that critiques the British landed gentry.",
    image: "https://example.com/pride.jpg",
    shelfId: "shelf-2",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "5e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5t",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description: "A story about teenage angst and alienation.",
    image: "https://example.com/catcher.jpg",
    shelfId: "shelf-3",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "6e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5u",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy novel about the adventures of Bilbo Baggins.",
    image: "https://example.com/hobbit.jpg",
    shelfId: "shelf-3",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "7e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5v",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    description: "A dystopian novel about a future where books are banned.",
    image: "https://example.com/fahrenheit.jpg",
    shelfId: "shelf-4",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "8e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5w",
    title: "Brave New World",
    author: "Aldous Huxley",
    description: "A dystopian novel about a technologically advanced society.",
    image: "https://example.com/brave.jpg",
    shelfId: "shelf-4",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "9e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5x",
    title: "Moby Dick",
    author: "Herman Melville",
    description: "A novel about the obsession with hunting a giant whale.",
    image: "https://example.com/mobydick.jpg",
    shelfId: "shelf-5",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "10e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5y",
    title: "War and Peace",
    author: "Leo Tolstoy",
    description: "A historical novel that intertwines the lives of several families.",
    image: "https://example.com/warandpeace.jpg",
    shelfId: "shelf-5",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "11e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5z",
    title: "The Odyssey",
    author: "Homer",
    description: "An epic poem about Odysseus's journey home.",
    image: "https://example.com/odyssey.jpg",
    shelfId: "shelf-6",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "12e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o6a",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    description: "A philosophical novel exploring morality and faith.",
    image: "https://example.com/karamazov.jpg",
    shelfId: "shelf-6",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "13e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o6b",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    description: "A novel about the moral dilemmas of a young man.",
    image: "https://example.com/crime.jpg",
    shelfId: "shelf-7",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "14e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o6c",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description: "A novel about vanity and moral duplicity.",
    image: "https://example.com/dorian.jpg",
    shelfId: "shelf-7",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "15e1b2c3d-4e5f-6g7h-8i9j-0k1l2m3n4o6d",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A novel about following one's dreams.",
    image: "https://example.com/alchemist.jpg",
    shelfId: "shelf-8",
    created_at: new Date(),
    updated_at: new Date(),
  },
];
